---
title: "Academic"
format: html
---

-   [Milestone 2](https://uoneduau-my.sharepoint.com/:b:/g/personal/c3541851_uon_edu_au/IQA15MmIEld5QYawcTwL0-GCAceaBysOvIOeiDeDH4J_Ic0?e=EIQavm) - PhD plan (Sept., 2025)

-   [Ph.D guide, 2025](https://uoneduau-my.sharepoint.com/:b:/g/personal/c3541851_uon_edu_au/IQB4pq2tYPtLSoej_B7-lVaUAa_NCshGv9-ie3jnbzbf4MU?e=hFb1hD) (Oct., 2025)

    *Legacy of Milestone 2, this document further details the aims, objectives, methods, expectations, collaborations of my PhD project and unroll the potential Chapters one by one.*

-   [Milestone 4](https://uoneduau-my.sharepoint.com/:b:/g/personal/c3541851_uon_edu_au/IQBan0DbW_0FTqUeFeS_TMFOAUbrxKCOfsRtDeQDf3pd3_Y?e=x2if4d) - Confirmation **document** (May, 2026)

    *Plan of the PhD research project, finalised at ten months mark after commencement. Provides a critical literature review which highlights knowledge gaps and suggest different chapters to address those.*

-   [Milestone 4](https://uoneduau-my.sharepoint.com/:b:/g/personal/c3541851_uon_edu_au/IQAttXi8inqWRrDiD7P2Kca5AZIh8ra8qRKBTcwhbbFFRkY?e=ewsobk) - Confirmation **presentation** (May, 2026)

    *Visual presentation of the PhD Thesis plan and objectivs. Summary of the Confirmation document.*

-   [Planning](https://uoneduau-my.sharepoint.com/:x:/g/personal/c3541851_uon_edu_au/IQDBgWd3rvn3RJvcYBUtb-rCAQjIKtJghwwbHYpe8Q-Snwk?e=bm8o8s) (Aug., 2026)

    *Time line and retro-planning of tasks and practical objectives to meet so the PhD is ensured to be achieved on schedule.*
