---
title: "Internal documents"
format: html
---

## Protocols

-   [Basics_for_Motus_Array\_&\_Tags, 2025](https://uoneduau-my.sharepoint.com/:b:/g/personal/c3541851_uon_edu_au/IQC0S_P_l1ENSK_RHL_2PhpxAahaHAgEHkv0UgN3ezw8ejE?e=n6lHst)

    *Handy protocol that describe how to connect to your SG receivers with a local Wi-Fi or GSM network, so you can check current time tag detections, but also download raw data from your receivers. How to activate/deactivate a Lotek nano-tags. Tips on tracker model decision related to ratio bird weight/tag weight so you remain under the 3% of individual body mass for equipment.* 

-   [Motus_tag_specs_and_species_list, 2025](https://docs.google.com/spreadsheets/d/1snJpWUXllw9LFXxo-GxCXkQ45V_f5z_WSXP79ntncRA/edit?pli=1&gid=0#gid=0)

    *See what Motus Lotek tag you can use depending the species of shorebird you aim to equip. Find also a dynamic table for pricing.*

## Log-books

-   [Trapping_records](https://uonstaff.sharepoint.com/:x:/r/sites/StudentGroupPhD-LouiseWilliamsandMatteaTaylor/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7Ba23e66f0-c551-4ba4-acd0-de0d5e83ca42%7D&wdOrigin=TEAMS-MAGLEV.teamsSdk_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=175385)

    Keep tracking the number of individuals trapped and against what protocols. Other details on the birds too (biometry and banding)

-   [MOTUS_Tag_records](https://uoneduau-my.sharepoint.com/:w:/g/personal/c3541851_uon_edu_au/IQDjSf_9maEVQraUIrYpDu5NAQLrHe15pg2NDOwKBC03W0c?e=7oohiZ)

    Keep tracking what Motus tag has been deployed. Bird flag and capture date detailed.

-   Motus_VHF_stations_state

    *(to be done)*

## Workshop notes

-   [2026_Virtual_Motus_Workshop](https://uoneduau-my.sharepoint.com/:b:/g/personal/c3541851_uon_edu_au/IQCtzPadfDgoRqsyECdzyM7RAd2MVTvX9XaqM7U44dhsJdo?e=FeVVr2)

## Miscellaneous

-   [Tide_forecasts_for_Newcastle_NSW](https://www.tide-forecast.com/locations/Newcastle-Australia/tides/latest)
