---
title: "Scientific"
format: html
---

## Scientific papers

-   2026 *(in preparation)* - [Estuarine movements from resident and migratory shorebirds on their non-breeding ground in Australia: Motus automated telemetry highlights a balance between circadian and tidal cycles](https://docs.google.com/document/d/1bJ2VcW-EwPwJnT2ijhElo17LMyAgwUNw4c06vjIEZ7c/edit?usp=sharing)

## Conferences

### Chapter 1 - Motus

-   2026 June - [Motus automated telemetry uncovers migratory shorebirds habitat selection, supporting adaptive land management](https://meetingorganizer.copernicus.org/WBF2026/WBF2026-603.html), World Biodiversity Forum (WBF), Davos, Switzerland, **Abstract**.

-   2026 June - [Motus automated telemetry uncovers migratory shorebirds habitat selection, supporting adaptive land management](https://uoneduau-my.sharepoint.com/:b:/g/personal/c3541851_uon_edu_au/IQCYWEsLVVvkQ5tp82DQj-LVAab16lUU2_mAm9kXlkLwd9A?e=8lqH1n), World Biodiversity Forum (WBF), Davos, Switzerland, **Presentation**.

-   2025 June - [Motus automated telemetry reveals new insights into nocturnal and low tide habitat use is coastal shorebirds](https://uoneduau-my.sharepoint.com/:b:/g/personal/c3541851_uon_edu_au/IQB-d7czEQuOQqIlka1ECJHOAW9zt85JS6Go256avSQF7zo?e=VZSK8U), Australasian Ornithological Conference (AOC), Perth, WA, **Abstract**.

-   2025 October - [MOTUS automated telemetry does not quite reveal habitat use from estuarine shorebirds](https://uoneduau-my.sharepoint.com/:b:/g/personal/c3541851_uon_edu_au/IQAzJZXB7A4_Qruc9TMUDII-ARsJB_hgkJhB0gTTcMguXOA?e=Aspzfx), Australian Ornithological Conference (AOC), Perth, WA, **Presentation**.

-   2025 June - [Motus automated telemetry uncovers mightatory shorebirds habitat selection, supporting adaptative land management](https://uoneduau-my.sharepoint.com/:b:/g/personal/c3541851_uon_edu_au/IQA9fmHl4hBvTZ2nyICgXKAzAZh4FQPAJ0gJTsKCioBWNBQ?e=XymyZC), Ecological Society of Australia (ESA), Adelaide, SA, **Abstract**.

-   2025 October - [MOTUS automated telemetry does not quite yet reveal habitat use from estuarine shorebirds](https://uoneduau-my.sharepoint.com/:b:/g/personal/c3541851_uon_edu_au/IQDk0spslustTp0ergZ4X-llAbruqNFNHZ1Ov51KZTSM9dw?e=WlUjbj), Ecological Society of Australia (ESA), Adelaide, SA, **Presentation**.
